version: '3.8'

services:
  db-ch:
    image: mysql:8.0
    container_name: db-ch
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bdd_mspr_api
    volumes:
      - db_data_ch:/var/lib/mysql
    ports:
      - "3330:3306"   # MySQL Suisse
    networks:
      - ch_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  api-ch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-ch
    environment:
      - PAYS_CIBLE=CH
    ports:
      - "3030:3001"   # API Suisse
    depends_on:
      db-ch:
        condition: service_healthy
    command: ["node", "server.js"]
    networks:
      - ch_network

  phpmyadmin-ch:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-ch
    environment:
      PMA_HOST: db-ch
      PMA_PORT: 3306
    ports:
      - "8092:80"     # PhpMyAdmin Suisse
    networks:
      - ch_network

volumes:
  db_data_ch:

networks:
  ch_network:
    driver: bridge
