version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-certs:/etc/nginx/certs
    networks:
      - fr_network
      - us_network
      - ch_network

networks:
  fr_network:
    external: true
    name: mspr_fr_network
  us_network:
    external: true
    name: mspr_us_network
  ch_network:
    external: true
    name: mspr_ch_network
