version: '3.8'

services:
  db-us:
    image: mysql:8.0
    container_name: db-us
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bdd_mspr_api
    volumes:
      - db_data_us:/var/lib/mysql
    ports:
      - "3320:3306"  
    networks:
      - us_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  api-us:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-us
    environment:
      - PAYS_CIBLE=US
      - DB_HOST=db-us
    ports:
      - "3020:3001"  
    depends_on:
      db-us:
        condition: service_healthy
    networks:
      - us_network

  phpmyadmin-us:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-us
    environment:
      PMA_HOST: db-us
      PMA_PORT: 3306
    ports:
      - "8091:80"   
    networks:
      - us_network

volumes:
  db_data_us:

networks:
  us_network:
    driver: bridge
