events {}

http {
    upstream api_fr {
        server api-fr:3001;
    }
    upstream api_us {
        server api-us:3001;
    }
    upstream api_ch {
        server api-ch:3001;
    }

    server {
        listen 443 ssl;
        server_name simOMS.fr;

        ssl_certificate /etc/nginx/certs/simOMS.fr+2.pem;
        ssl_certificate_key /etc/nginx/certs/simOMS.fr+2-key.pem;

        location / {
            proxy_pass http://api_fr;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl;
        server_name simOMS.us;

        ssl_certificate /etc/nginx/certs/simOMS.fr+2.pem;
        ssl_certificate_key /etc/nginx/certs/simOMS.fr+2-key.pem;

        location / {
            proxy_pass http://api_us;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl;
        server_name simOMS.ch;

        ssl_certificate /etc/nginx/certs/simOMS.fr+2.pem;
        ssl_certificate_key /etc/nginx/certs/simOMS.fr+2-key.pem;

        location / {
            proxy_pass http://api_ch;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
