events {}

http {
    upstream api_fr {
        server api-fr:3001;
    }
    upstream api_us {
        server api-us:3001;
    }
    upstream api_ch {
        server api-ch:3001;
    }

    server {
        listen 80;
        server_name simOMS.fr;

        location / {
            proxy_pass http://api_fr;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name simOMS.us;

        location / {
            proxy_pass http://api_us;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name simOMS.ch;

        location / {
            proxy_pass http://api_ch;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
