Set-Location "C:\Users\Tristan\Desktop\epsi taff\mspr"

@'
sonar.projectKey=mspr
sonar.projectName=mspr
sonar.host.url=http://localhost:9000

sonar.sources=api
sonar.inclusions=**/*.js,**/*.jsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,api/tests/**,**/*.test.*,**/*.spec.*,**/*.min.js,**/*.sql,**/*.py
sonar.coverage.exclusions=**/*
sonar.scm.disabled=true

# JS analyzer (mémoire Node pour l'eslint-bridge)
sonar.javascript.node.maxspace=2048
# (optionnel) pointer explicitement vers Node si besoin :
# sonar.nodejs.executable=C:\\Program Files\\nodejs\\node.exe
'@ | Set-Content -Encoding UTF8 .\sonar-project.properties
